# Generated by Django 5.2 on 2025-10-17 11:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceReason',
            fields=[
                ('reason_code', models.IntegerField(help_text='e.g., 1-28', primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=30.0, max_digits=6)),
                ('transportation_expense', models.IntegerField()),
                ('distance_from_residence_to_work', models.IntegerField()),
                ('service_time', models.IntegerField()),
                ('age', models.IntegerField()),
                ('work_load_average_day', models.FloatField()),
                ('hit_target', models.IntegerField()),
                ('education', models.IntegerField(help_text='1:High School, 2:Graduate, 3:Postgrad, 4:Doctor')),
                ('body_mass_index', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AbsenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_logged', models.DateField(default=django.utils.timezone.now)),
                ('predicted_hours', models.FloatField()),
                ('status', models.CharField(choices=[('ABSENT', 'Currently Absent'), ('RETURNED', 'Returned to Work')], default='ABSENT', max_length=10)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.absencereason')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.employee')),
            ],
        ),
    ]
